CREATE OR REPLACE PROCEDURE TEST_SP( NROWS IN INTEGER, OFFSET IN INTEGER DEFAULT 0 ) AS
  BEGIN
    DELETE FROM TABLE_FOR_TEST_SP;
    FOR I IN 1..NROWS LOOP
      INSERT INTO TABLE_FOR_TEST_SP VALUES ( I, I + OFFSET );
    END LOOP;
  END;
/
